apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  silenceAutosupport: false
  autosupportImage: "netapp/trident-autosupport:21.04"
  autosupportProxy: "http://proxy.example.com:8888"
